export const data = [
  {
    id: "1",
    dateAdded: 12345,
    title: "Grey tee shirt ",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 450,
    priceBefore: 550,
    Available: true,
    categories: ["men", "clothing"],
    imageUrls: [
      "https://i.ibb.co/wryv2RK/tee-2-893x1024.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "2",
    dateAdded: 12346,

    title: "Black T-Shirt",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 500,
    priceBefore: 550,
    Available: true,
    categories: ["men", "clothing"],
    imageUrls: [
      "https://i.ibb.co/CbJF6TX/tee-1-1000x1000.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "3",
    dateAdded: 12347,

    title: "High hill",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "leather" },
      { key: "BRAND", value: "apex" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 4500,
    priceBefore: 4750,
    Available: true,
    categories: ["women", "shoes", "category3"],
    imageUrls: ["https://i.ibb.co/X87Q2wH/women-shoes-1-882x1024.png"],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "4",
    dateAdded:12348,

    title: "Swimsuit",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 9500,
    priceBefore: 9950,
    Available: true,
    categories: ["women", "clothing"],
    imageUrls: [
      "https://i.ibb.co/3MbVjNp/swimsuit-1-800x800.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "5",
    dateAdded:12349,

    title: "Grey shorts",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 800,
    priceBefore: 950,
    Available: true,
    categories: ["men", "clothing", "kid's"],
    imageUrls: [
      "https://i.ibb.co/1ZKv2jw/shorts-1-480x480.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "6",
    dateAdded: 12545,
    title: "Black shirt",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 1500,
    priceBefore: 1850,
    Available: true,
    categories: ["men", "clothing"],
    imageUrls: [
      "https://i.ibb.co/1r30VJv/shirt-1-950x950.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "7",
    dateAdded:12365,

    title: "Black Shoes",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "leather" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 3500,
    priceBefore: 4550,
    Available: true,
    categories: ["men", "shoes"],
    imageUrls: [
      "https://i.ibb.co/WVw64sw/men-shoe-2000x2000.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ["Black", "brown"],
  },
  {
    id: "8",
    dateAdded:12375,

    title: "Kid's romper",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 1000,
    priceBefore: 1200,
    Available: true,
    categories: ["kid's", "clothing"],
    imageUrls: [
      "https://i.ibb.co/0sKtLNw/romper-1-320x400.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "9",
    dateAdded:12355,

    title: "Kid's shoes",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "plastic" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 700,
    priceBefore: 900,
    Available: true,
    categories: ["kid's", "shoes"],
    imageUrls: [
      "https://i.ibb.co/2dy2Mwm/kid-shoe-2-900x900.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "10",
    dateAdded: 12546,
    title: "Kid's hoodie",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 1600,
    priceBefore: 1700,
    Available: true,
    categories: ["kid's", "clothing"],
    imageUrls: [
      "https://i.ibb.co/q7781Tz/hoodie-2-800x800.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Pink"],
  },
  {
    id: "11",
    dateAdded: 12547,
    title: "Hoodie",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Cotton" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 1000,
    priceBefore: 1100,
    Available: true,
    categories: ["men", "clothing"],
    imageUrls: [
      "https://i.ibb.co/6F2rj6s/hoodie-1-500x500.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Grey"],
  },
  {
    id: "12",
    dateAdded: 12548,
    title: "Belt",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "leather" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 400,
    priceBefore: 500,
    Available: true,
    categories: ["men", "gears"],
    imageUrls: [
      "https://i.ibb.co/2kQjQ95/gear-4-belt-2000x2000.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
  },
  {
    id: "13",
    dateAdded: 12549,
    title: "Basketball",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Leather,Plastic" },
      { key: "BRAND", value: "Nike" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 3000,
    priceBefore: 3200,
    Available: true,
    categories: ["kid's", "men", "gears"],
    imageUrls: [
      "https://i.ibb.co/WvyS9d7/gear-5-795x797.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["5", "6", "7", "8"],
    colors: [],
  },
  {
    id: "13",
    dateAdded: 12550,
    title: "Mask",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "Plastic" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 100,
    priceBefore: 120,
    Available: true,
    categories: ["kid's", "men", "gears"],
    imageUrls: [
      "https://i.ibb.co/cFBFnLt/gear-3-mask-665x652.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: [],
    colors: [],
  },
  {
    id: "14",
    dateAdded: 12551,
    title: "Space Suit",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "BRAND", value: "Space X" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 40000,
    priceBefore: 62000,
    Available: true,
    categories: ["kid's", "men", "women", "gears"],
    imageUrls: [
      "https://i.ibb.co/WfbTcDp/gear-1-1600x1600.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [],
  },
  {
    id: "15",
    dateAdded: 12552,
    title: "Hand bag",
    descriptions: [
      { key: "PRODUCT ID", value: "01" },
      { key: "MATERIAL", value: "leather" },
      { key: "BRAND", value: "Yellow" },
    ],
    details:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus aliquid animi consequuntur distinctio dolor dolore dolores est fugiat hic, illum inventore ipsum magnam maxime, molestiae mollitia placeat quam, quos ratione sit vitae. Ab alias asperiores aut blanditiis consequatur eius explicabo harum ipsa nam nisi nostrum possimus praesentium quia, quisquam quo quos repellat reprehenderit suscipit ullam utpak.",
    priceCurrent: 10000,
    priceBefore: 12000,
    Available: true,
    categories: ["women", "gears"],
    imageUrls: [
      "https://i.ibb.co/7KGd6Rq/gear-2-bag-1000x1000.png",
      "https://i.ibb.co/Tm0bpM8/jackets.png",
      "https://i.ibb.co/hdjbbSC/grey-tee-1.png",
    ],
    reviews: [
      {
        user: "Gonu Molla",
        rating: 2,
        date: "3 April 2021",
        userReview: "This product is disfunctional just like me.",
      },
      {
        user: "Tanvir",
        rating: 5,
        date: "5 April 2021",
        userReview: "Long lasting.",
      },
      {
        user: "Arko",
        rating: 4,
        date: "13 April 2021",
        userReview: "Feels good.",
      },
    ],
    sizes: [],
    colors: ["black", "pink", "red"],
  },
];
